name: Build and publish epimind to Docker Hub
on:
    [workflow_dispatch]
jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: build image
              run: docker buildx build --platform linux/amd64 -t epimind:latest -t epimind:v0.0.1 .
            - name: push image to docker hub
              run: |
                  docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
                  docker push ${{ secrets.DOCKER_HUB_USER }}/epimind:latest


            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v1
            # - name: Build and push
            #   run: |
            #       docker buildx build --platform linux/amd64,linux/arm64 -t epimind:latest .
            #       echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            #       docker tag epimind:latest ${{ secrets.DOCKER_USERNAME }}/epimind:latest
            #       docker push ${{ secrets.DOCKER_USERNAME }}/epimind:latest